# Generated by Django 3.2.9 on 2021-11-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('about', models.TextField(blank=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.manager')),
            ],
        ),
    ]
