# Generated by Django 3.2.9 on 2021-11-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name_task', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField()),
                ('property', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Manager.manager')),
            ],
        ),
    ]
